export type Horse = {
  post: number;
  name: string;
  jockey: string;
  trainer: string;
  odds: string;
  oddsNum: number;
  fact: string;
  postColor: string;
  postColorSecondary?: string;
  postColorPattern?: "solid" | "diagonal" | "halves";
  postTextDark: boolean;
  coatColor: string;
  coatType: string;
  scratched?: boolean;
};

export const HORSES: Horse[] = [
  {
    post: 1,
    name: "Renegade",
    jockey: "Irad Ortiz Jr.",
    trainer: "Todd Pletcher",
    odds: "4-1",
    oddsNum: 4,
    fact: "The favorite drew the worst gate — post 1. But trainer Pletcher has conquered it before.",
    postColor: "#CC0000",
    postTextDark: false,
    coatColor: "#8B4513",
    coatType: "Bay",
  },
  {
    post: 2,
    name: "Albus",
    jockey: "Manny Franco",
    trainer: "Riley Mott",
    odds: "30-1",
    oddsNum: 30,
    fact: "Shares a barn with Incredibolt — trainer Riley Mott swings two shots at glory today.",
    postColor: "#FFFFFF",
    postTextDark: true,
    coatColor: "#BEBEBE",
    coatType: "Gray",
  },
  {
    post: 3,
    name: "Intrepido",
    jockey: "Hector Berrios",
    trainer: "Jeff Mullins",
    odds: "55-1",
    oddsNum: 55,
    fact: "A West Coast long shot who surprised everyone just by making the field.",
    postColor: "#0000CC",
    postTextDark: false,
    coatColor: "#CD853F",
    coatType: "Chestnut",
  },
  {
    post: 4,
    name: "Litmus Test",
    jockey: "Martin Garcia",
    trainer: "Bob Baffert",
    odds: "34-1",
    oddsNum: 34,
    fact: "Trained by the legendary Bob Baffert, who has more Derby wins than almost anyone alive.",
    postColor: "#FFDD00",
    postTextDark: true,
    coatColor: "#8B4513",
    coatType: "Bay",
  },
  {
    post: 5,
    name: "Robusta",
    jockey: "Cristian Torres",
    trainer: "Doug O'Neill",
    odds: "30-1",
    oddsNum: 30,
    fact: "Named after a type of coffee — earned his spot when Right to Party scratched late.",
    postColor: "#006400",
    postTextDark: false,
    coatColor: "#CD853F",
    coatType: "Chestnut",
  },
  {
    post: 6,
    name: "Commandment",
    jockey: "Luis Saez",
    trainer: "Brad Cox",
    odds: "7-1",
    oddsNum: 7,
    fact: "Brad Cox also sends Further Ado (post 18) — even the trainer has to pick a favorite!",
    postColor: "#111111",
    postTextDark: false,
    coatColor: "#CD853F",
    coatType: "Chestnut",
  },
  {
    post: 7,
    name: "Danon Bourbon",
    jockey: "Atsuya Nishimura",
    trainer: "Manabu Ikezoe",
    odds: "20-1",
    oddsNum: 20,
    fact: "Japan's best chance at Derby glory — the Danon connections have been dreaming of this since 2018.",
    postColor: "#FF6600",
    postTextDark: false,
    coatColor: "#8B4513",
    coatType: "Bay",
  },
  {
    post: 8,
    name: "So Happy",
    jockey: "Mike Smith",
    trainer: "Mark Glatt",
    odds: "15-1",
    oddsNum: 15,
    fact: "Hall of Famer Mike Smith rides — he won the 2018 Derby on Justify. Can lightning strike twice?",
    postColor: "#FF1493",
    postTextDark: false,
    coatColor: "#8B4513",
    coatType: "Bay",
  },
  {
    post: 9,
    name: "The Puma",
    jockey: "Javier Castellano",
    trainer: "Gustavo Delgado",
    odds: "10-1",
    oddsNum: 10,
    fact: "Unbeaten at Churchill Downs — two workouts at the track have him razor sharp.",
    postColor: "#00CED1",
    postTextDark: false,
    coatColor: "#8B4513",
    coatType: "Bay",
  },
  {
    post: 10,
    name: "Wonder Dean",
    jockey: "Ryusei Sakai",
    trainer: "Daisuke Takayanagi",
    odds: "30-1",
    oddsNum: 30,
    fact: "Japan's second entry, owned by a syndicate that includes a famous J-pop idol.",
    postColor: "#800080",
    postTextDark: false,
    coatColor: "#8B4513",
    coatType: "Bay",
  },
  {
    post: 11,
    name: "Incredibolt",
    jockey: "Jaime Torres",
    trainer: "Riley Mott",
    odds: "20-1",
    oddsNum: 20,
    fact: "Stablemate of Albus — trainer Riley Mott has two tickets in today's lottery.",
    postColor: "#808080",
    postTextDark: false,
    coatColor: "#4A2C0A",
    coatType: "Dark Bay",
  },
  {
    post: 12,
    name: "Chief Wallabee",
    jockey: "Junior Alvarado",
    trainer: "Bill Mott",
    odds: "8-1",
    oddsNum: 8,
    fact: "The Ball family's first Derby horse in 55 years — trained by Hall of Famer Bill Mott.",
    postColor: "#228B22",
    postTextDark: false,
    coatColor: "#9E9E9E",
    coatType: "Gray",
  },
  {
    post: 13,
    name: "Great White",
    jockey: "Alex Achard",
    trainer: "John Ennis",
    odds: "50-1",
    oddsNum: 50,
    fact: "Crept into the field when Silent Tactic scratched — a total wild card with nothing to lose.",
    postColor: "#D2B48C",
    postTextDark: true,
    coatColor: "#E0E0E0",
    coatType: "Gray",
  },
  {
    post: 14,
    name: "Potente",
    jockey: "Juan Hernandez",
    trainer: "Bob Baffert",
    odds: "20-1",
    oddsNum: 20,
    fact: "Baffert's second gun — been clocking some of the fastest workouts at Churchill Downs.",
    postColor: "#9ACD32",
    postTextDark: true,
    coatColor: "#8B4513",
    coatType: "Bay",
  },
  {
    post: 15,
    name: "Emerging Market",
    jockey: "Flavien Prat",
    trainer: "Chad Brown",
    odds: "15-1",
    oddsNum: 15,
    fact: "Chad Brown is one of the best trainers in the business — pointed at this race all year.",
    postColor: "#8B4513",
    postTextDark: false,
    coatColor: "#BEBEBE",
    coatType: "Gray",
  },
  {
    post: 16,
    name: "Pavlovian",
    jockey: "Edwin Maldonado",
    trainer: "Doug O'Neill",
    odds: "30-1",
    oddsNum: 30,
    fact: "O'Neill won the 2012 Derby with I'll Have Another. This chestnut hopes to ring the bell again.",
    postColor: "#CC0000",
    postColorSecondary: "#0000CC",
    postColorPattern: "diagonal",
    postTextDark: false,
    coatColor: "#CD853F",
    coatType: "Chestnut",
  },
  {
    post: 17,
    name: "Six Speed",
    jockey: "TBD",
    trainer: "Bhupat Seemar",
    odds: "50-1",
    oddsNum: 50,
    fact: "Pure speed from gate to wire — the question is whether he can last the full 1¼ miles.",
    postColor: "#FFFFFF",
    postColorSecondary: "#111111",
    postColorPattern: "diagonal",
    postTextDark: false,
    coatColor: "#5C3317",
    coatType: "Dark Bay",
  },
  {
    post: 18,
    name: "Further Ado",
    jockey: "John Velazquez",
    trainer: "Brad Cox",
    odds: "6-1",
    oddsNum: 6,
    fact: "Won the Bluegrass Stakes and is Brad Cox's top choice despite drawing the tough outside post.",
    postColor: "#FFDD00",
    postColorSecondary: "#006400",
    postColorPattern: "halves",
    postTextDark: true,
    coatColor: "#5C3317",
    coatType: "Dark Bay",
  },
  {
    post: 19,
    name: "Golden Tempo",
    jockey: "Jose Ortiz",
    trainer: "Cherie DeVaux",
    odds: "30-1",
    oddsNum: 30,
    fact: "Trained by one of racing's rare female trainers — quietly improving all spring.",
    postColor: "#ADD8E6",
    postTextDark: false,
    coatColor: "#CD853F",
    coatType: "Chestnut",
  },
  {
    post: 20,
    name: "Ocelli",
    jockey: "Joe Ramos",
    trainer: "D.W. Beckman",
    odds: "50-1",
    oddsNum: 50,
    fact: "Named after the simple eyes of butterflies — a last-second alternate with a beautiful story.",
    postColor: "#001F5B",
    postColorSecondary: "#FFD700",
    postColorPattern: "halves",
    postTextDark: false,
    coatColor: "#8B4513",
    coatType: "Bay",
  },
];

export function getOddsTier(oddsNum: number): "gold" | "silver" | "bronze" {
  if (oddsNum <= 10) return "gold";
  if (oddsNum <= 20) return "silver";
  return "bronze";
}
